### ISSUE TITLE
Update version numbering in commit c34f4405a8ffca9a6e69041d1108d0931b9c49a1

### ISSUE THREAD

**Issue by OtakuSenpai** [BurdIRC/burd#12]
* *Burd IRC Version:* 0.5.6 (from git repo,actual 0.5.9)
* *Operating System:* Void Linux

** Please explain in detail what your issue or bug is. This will help us fix the issue. **
Please update the version number in burdirc. I had issues building burd from scratch in the current master and had to get help from duckgoose.

     Also a notification to upgrade to burd 0.5.9 was issued by the executable after running. Idk if its related.

**Comment by TheDetectiveTaco** [comment]
GitHub repo hasn't been updated since 0.5.6. Plan to update when next version is released.
