### ISSUE TITLE
Make channel modes apparent in a window

### ISSUE THREAD

**Issue by OtakuSenpai** [BurdIRC/burd#13]
** Please explain in detail what features or enhancements you would like to see added to Burd IRC. Please take into consideration that we may not add your features or enhancements that you requested. We are not required to add them. **

The Topic and User list of a channel are shown in Burd, but an important feature,aka the channel modes, arent displayed. Please add them below "Users Here" text which is above User list or anywhere you guys deem fit.

**Comment by haxednet** [comment]
I will consider adding modes to the UI. In the meantime you can do "/mode #channel" to view the current channel modes.
