### ISSUE TITLE
/whois command changes

### ISSUE THREAD

**Issue by TheDetectiveTaco** [BurdIRC/burd#14]
Make the /whois <nick> command use /whois <nick> <nick> 

This will allow more information to be sent in the whois such as idle time, etc.

**Comment by KoraggKnightWolf** [comment]
I suppose you meant /whois nick nick instead of /whois nick ? Also for it but it must be clarified to users that often an IRCd whill respond with "no such server" rather than "no such nick/channel" when /whois nick nick is used on a nickname not on IRC.

Regards,

Koragg

**Comment by haxednet** [comment]
"/wii" is the standard way of doing "whois nick nick". If we make make /whois send the nick twice, then
A: this will be deviating from the norm. is this something we want to do?
B: do all irc servers support this?

**Comment by TheDetectiveTaco** [comment]
We could do it. It depends. As @KoraggKnightWolf mentioned to me on IRC it will output a "Server not found" or similar message if the user is not online instead of the regular error message. There are other clients who do /Whois nick nick as the standard /Whois nick

**Comment by TheDetectiveTaco** [comment]
I think that we can keep the method that is currently being used. (/wii being used to show the Whois + idle time, etc and /Whois to show the basic Whois info)
