### ISSUE TITLE
SASL plain username issue

### ISSUE THREAD

**Issue by TheDetectiveTaco** [BurdIRC/burd#18]
Burd IRC does not save the SASL Plain username. In the latest git build of burd add a network, choose SASL plain auth enter a username and password. Then save the new network and try and edit it and the SASL plain username field will be empty.

**Comment by haxednet** [comment]
networks/edit.js line 61 shows: $("input#sasl_user").val(newServer.auth.user);
it should be: $("input#sasl_user").val(newServer.auth.username);

this should be resolved now.
