### ISSUE TITLE
Menu buttons appear blurry

### ISSUE THREAD

**Issue by KoraggKnightWolf** [BurdIRC/burd#6]
It appears that the main 3 menu bottons to the bottom left appear blurry, at least on my laptop, which has a full hd resolution on a 17.3 inches screen.
A screenshot is provided below in the hopes that the issue is noticeable.

![unbenannt](https://user-images.githubusercontent.com/31944041/44823089-997dc700-abfe-11e8-81cc-6eec74abaf01.png)

**Comment by haxednet** [comment]
added css option "image-rendering: -webkit-optimize-contrast;" to resolve issue
