### ISSUE TITLE
Make Chat Settings configureable per-network and include a "Show topic messages" toggle

### ISSUE THREAD

**Issue by KoraggKnightWolf** [BurdIRC/burd#7]
Some might wish to only hide joins/parts/quits on very large, inactive channels (e.g. on freenode) but might wish to see them on smaller channels/networks. Also a very common channel event is topic changes which users might also wish to toggle. Perhaps also add an option for /names and /whois as some wish to also have those displayed in channel (others, such as /notice, are thinkiable as well, it is a non-exhaustive list). 
Some might also wish to only log certain channels (help/support channels, channels they op in, etc) so being able to have more options configurable per-network would also help in that regard.

**Comment by TheDetectiveTaco** [comment]
Will consider adding in the future. More important issues that need to be fixed before these kinds of luxury features are added.
