### ISSUE TITLE
Make On-Connect commands show as "one per line" vs "comma seperated list"

### ISSUE THREAD

**Issue by KoraggKnightWolf** [BurdIRC/burd#8]
The current implementation of on-connect commands as a comma seperated list in just a single line box can get very cluttered with many commands added, e.g. a lot of channels, perhaps modes set etc, making typoed channel names, mode chars etc. very difficult to spot in such an environment.
Perhaps an approach where one command per line is given could help to make things not only be more aesthetically appealing but also way easier to navigate to and find options to change (e.g. removing one previously auto joined channel). Perhaps even make auto-join an entirely seperate menu item.
Also, a JOIN example is given without the prefixed / are on-connect commands to be given with or without a / in this client?

Regards,

Koragg

**Comment by TheDetectiveTaco** [comment]
@duckgoose what would you think about a separate page for this? Like when you add or edit a network there is a button that will take you to a page for on connect commands.

**Comment by TheDetectiveTaco** [comment]
Will consider adding in the future. More important issues and things need to be added and fixed before luxury features like these are added.
