### ISSUE TITLE
Maximizing and "de-maximizing" cause menu items to be auto closed or not scale in size accordingly

### ISSUE THREAD

**Issue by KoraggKnightWolf** [BurdIRC/burd#9]
When maximizing the client (or pressing the maximize button again to "de-maximize" the progragm) leads to the menu and settings to be closed and if the right most button at the bottom left is opened, those items remain where they were previously. Screenshots displaying the last issue will be supplied. 

Edit on testing: Going from maximum to small size does not appear to cause the last option to remain open but closes it like the others.

![after_max](https://user-images.githubusercontent.com/31944041/44824264-ec5a7d00-ac04-11e8-86ff-c420111b1a20.png)
![before_max](https://user-images.githubusercontent.com/31944041/44824265-ec5a7d00-ac04-11e8-9893-92bc2bddd4fb.png)

**Comment by haxednet** [comment]
resolved as of 0.5.9
